# FROM node:latest
FROM node:20-bookworm-slim AS builder
LABEL maintaner='y-yoshimoto'
# 環境変数を設定する
#ENV NODE_ENV=production
ENV NODE_ENV=development
ENV APPNAME=app

# アプリケーションディレクトリ作成/コピー
RUN mkdir -p /$APPNAME
WORKDIR /$APPNAME
# パッケージインストール
COPY ./app/package.json /$APPNAME/package.json
RUN yarn install
#RUN yarn global add vite && yarn install
# アプリケーションのビルド
COPY ./app/ /$APPNAME
RUN yarn build
# CMD ["tail", "-f", "/dev/null"]

# React App set Nginx
FROM nginx
LABEL  maintainer "y.yoshimoto"
ENV APPNAME=app
# コンテツファイルの設置
COPY --from=builder /$APPNAME/dist/ /usr/share/nginx/html/
RUN mkdir -p /usr/share/nginx/html/sampleData

# nginx設定ファイルの設置
COPY ./deploy/nginx.conf /etc/nginx/nginx.conf
COPY ./deploy/server.conf /etc/nginx/conf.d/server.conf

# コンテナ実行時の動作設定
EXPOSE 80 443 3000
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
