# Yarnインストールコンテナ
FROM node:20-bookworm-slim
LABEL maintaner='y-yoshimoto'
# アプリケーションディレクトリ名指定
ARG APPNAME=app
# 環境変数を設定する
ENV NODE_ENV=development

# sudo, gitのインストール
RUN apt-get update && apt-get install -y sudo git curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

# 実行ユーザー追加
ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=1000
# RUN useradd -m -s /bin/bash -u $USER_UID -g $USER_GID $USERNAME \
#     && usermod -a -G 1000 $USERNAME

# アプリケーションのディレクトリ作成/権限変更
RUN mkdir -p /$APPNAME/src \
    && mkdir -p /$APPNAME/public \
    && mkdir -p /$APPNAME/.vscode 
RUN chown $USERNAME:dialout /$APPNAME/* \
    && chown $USERNAME:dialout /$APPNAME/.*

# package.jsonのコピー
COPY ./app/package.json /$APPNAME/package.json
#COPY ./app/*.json /$APPNAME/

# ユーザー変更/作業ディレクトリ変更
WORKDIR /$APPNAME

# yarnInstall
RUN sudo -u $USERNAME yarn install --dev --frozen-lockfile\
    && sudo -u $USERNAME yarn license-checker --summary >> ./LicenseSummary.txt \
    && sudo -u $USERNAME yarn license-checker --csv > Licenses.csv \
    && sudo -u $USERNAME yarn cache clean

# vite, vitestのコマンドエイリアス追加
RUN echo "alias vitest='/app/node_modules/vitest/vitest.mjs'" >> /etc/bash.bashrc \
    && echo "alias vite='/app/node_modules/vite/bin/vite.js'" >> /etc/bash.bashrc

# アプリケーションファイルのコピー/権限変更
COPY ./app/ /$APPNAME
RUN chown $USERNAME:dialout /$APPNAME/* \
    && chown $USERNAME:dialout /$APPNAME/.* \
    && chown $USERNAME:dialout /$APPNAME/.vscode/*

# 公開ポート設定
EXPOSE 3000 

CMD ["tail", "-f", "/dev/null"]
#CMD ["yarn", "start"]