version: "3.2"
services:
  # Portal React アプリケーション
  potral_c:
    image: potralpro_c
    build:
      context: potral_c
      dockerfile: Dockerfile_pro
    ports:
      - "3000:3000"
    # restart: always
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
      - VITE_ROUTER_BASENAME=${PRO_ROUTER_BASENAME}
      - VITE_MOCK_ENABLED=${PRO_MOCK_ENABLED}
    # command: yarn start
    stdin_open: true


  # リバースプロキシ
  nginxproxy_c:
    image: nginxproxy_c
    build: nginxproxy_c
    ports:
      - 80:80
    # restart: always
    environment:
      TZ: ${TZ}

  # API/APIプロキシ
  apiproxy_c:
    image: apiproxy_c
    build: apiproxy_c
    volumes:
      - ./apiproxy_c/contents/:/usr/src/app/contents/
    ports:
      - 8080:8080
    # restart: always
    environment:
      TZ: ${TZ}
