# FROM node:latest
FROM node:20-bookworm-slim AS builder
LABEL maintaner='y-yoshimoto'
# 環境変数を設定する
ENV NODE_ENV=production
ENV APPNAME=app

RUN mkdir -p /$APPNAME/src && mkdir -p /$APPNAME/public
WORKDIR /$APPNAME

COPY ./package.json /$APPNAME/package.json

RUN yarn install --production
COPY ./src /$APPNAME/src
COPY ./public /$APPNAME/public

RUN yarn build

# React App set Nginx
FROM nginx
LABEL  maintainer "y.yoshimoto"
ENV APPNAME SimpleTableApp
# コンテツファイルの設置
COPY --from=builder /$APPNAME/build/ /usr/share/nginx/html/
RUN mkdir -p /usr/share/nginx/html/sampleData
COPY ./sampleData /usr/share/nginx/html/sampleData

# nginx設定ファイルの設置
COPY nginx.conf /etc/nginx/nginx.conf
COPY server.conf /etc/nginx/conf.d/server.conf

# コンテナ実行時の動作設定
EXPOSE 80 443
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
