# Yarnインストールコンテナ
FROM node:20-bookworm-slim as yarninstall
LABEL maintaner='y-yoshimoto'
# アプリケーションディレクトリ名指定
ARG APPNAME=app
# 環境変数を設定する
ENV NODE_ENV=development

# アプリケーションのディレクトリ作成
RUN mkdir -p /$APPNAME/
# 作業ディレクトリ
WORKDIR /$APPNAME
# package.jsonのコピー
COPY ./app/package.json /$APPNAME/package.json
# yarnInstall
RUN yarn install --dev \
    && yarn license-checker --summary >> ./LicenseSummary.txt \
    && yarn license-checker --csv > Licenses.csv \
    && yarn cache clean


# 開発コンテナ用
FROM node:20-bookworm-slim
LABEL maintaner='y-yoshimoto'
# 環境変数を設定する
ENV NODE_ENV=development
# アプリケーションディレクトリ名指定
ARG APPNAME=app

# gitのインストール
RUN apt-get update && apt-get install -y git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 実行ユーザー追加
ARG USERNAME=vscode
ARG USER_UID=501
ARG USER_GID=20
RUN useradd -m -s /bin/bash -u $USER_UID -g $USER_GID $USERNAME \
    && usermod -a -G 1000 $USERNAME

# yarnパッケージのコピー
COPY --from=yarninstall /$APPNAME/ /$APPNAME/

# アプリケーションファイルのコピー/権限変更
COPY ./app/ /$APPNAME
RUN chown $USERNAME:dialout /$APPNAME/* \
    && chown $USERNAME:dialout /$APPNAME/.* \
    && chown $USERNAME:dialout /$APPNAME/.vscode/*


# ユーザー変更/作業ディレクトリ変更
USER $USERNAME
WORKDIR /$APPNAME

# 公開ポート設定
EXPOSE 3000 

CMD ["tail", "-f", "/dev/null"]
#CMD ["yarn", "start"]